# Generated by Django 4.0 on 2021-12-30 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=50, verbose_name='brand car')),
                ('model_car', models.CharField(max_length=50, verbose_name='model car')),
                ('vin_code', models.IntegerField(verbose_name='vin_code')),
                ('numberplate', models.CharField(max_length=10, verbose_name='number_plate')),
                ('color_car', models.CharField(max_length=30, verbose_name='Color')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(default='')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.car')),
                ('owner_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category')),
                ('cars', models.ManyToManyField(blank=True, related_name='categories', to='main_app.Car')),
                ('owner_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
