# Generated by Django 4.0 on 2021-12-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=50, verbose_name='brend car')),
                ('model_car', models.CharField(max_length=50, verbose_name='model car')),
                ('vincode', models.IntegerField(verbose_name='vincode')),
                ('numberplate', models.CharField(max_length=10, verbose_name='number_plate')),
                ('color_car', models.CharField(max_length=30, verbose_name='Color')),
            ],
        ),
    ]
